#!/bin/bash -f

AGHOME=`pwd`
HWNAME="project"
TESTING=

NAME=`jq .users\[0\].name "$AGHOME"/submission_metadata.json`
EMAIL=`jq .users\[0\].email "$AGHOME"/submission_metadata.json`
ASSIGNMENT=`jq -c .assignment.title "$AGHOME"/submission_metadata.json`

echo Welcome "$NAME" to autograder for "$ASSIGNMENT"

cd "$AGHOME"/submission

if [[ -d '__MACOSX' ]]; then
	rm -rf __MACOSX
fi

if [ `ls -1 | wc -l` -eq "1" ]
then
	cd `ls -1`
fi

if [ -d "${HWNAME}_files" ]
then
	cd ${HWNAME}_files
fi

if [ -d "$HWNAME" ]
then
	cd $HWNAME
fi

echo ""
echo Following file were found in your submission. 
echo Please ensure that all the files you want to submit are there.
echo ""

# based on https://unix.stackexchange.com/questions/9496/looping-through-files-with-spaces-in-the-names
OIFS="$IFS"
IFS=$'\n'
for f in `find . -type f | grep -v __MACOSX | grep -v DS_Store | grep -v Icon?`
do
  echo "$f: size=`wc -c $f | awk '{print $1;}'` md5sum=`md5sum $f | awk '{print $1;}'`"
done
IFS="$OIFS"

echo ""
echo Now checking for some of the required files \(not an exhaustive list\)
echo ""
# check required files
FILES="report.pdf video.url"

for f in $FILES
do
	rm -f "$AGHOME"/source/$f
	if test -f "$f"; then
		echo "Required file $f exists: size=`wc -c $f | awk '{print $1;}'` md5sum=`md5sum $f | awk '{print $1;}'`"
		cp $f "$AGHOME"/source/$f
	else
		echo "Required file $f not found."
	fi
done


cd "$AGHOME"/source

echo ""
echo "This project will be manually graded."
cat results_manual.json > "$AGHOME"/results/results.json
exit 0