#!/usr/bin/env bash

source /etc/profile.d/jdk14.sh

AGHOME=`pwd`

cd $AGHOME/source

wget -q -O run_autograder_helper https://www.dropbox.com/s/cyhg16hwi48eerf/run_autograder_helper?raw=1

chmod +x run_autograder_helper

cd $AGHOME

$AGHOME/source/run_autograder_helper