#!/bin/bash -f

AGHOME=`pwd`
HWNAME="final"
TESTING=

cd "$AGHOME"/submission

if [[ -d '__MACOSX' ]]; then
	rm -rf __MACOSX
fi

if [ `ls -1 | wc -l` -eq "1" ]
then
	cd `ls -1`
fi

if [ -d "${HWNAME}_files" ]
then
	cd ${HWNAME}_files
fi

if [ -d "$HWNAME" ]
then
	cd $HWNAME
fi

# based on https://unix.stackexchange.com/questions/9496/looping-through-files-with-spaces-in-the-names
OIFS="$IFS"
IFS=$'\n'
for f in `find . -type f | grep -v __MACOSX | grep -v DS_Store | grep -v Icon`
do
  wc -c "$f"
done
IFS="$OIFS"

echo ""

# check required files
FILES="final.circ fsm_2phs.fzm fsm_sqroot.fzm video.url"


for f in $FILES
do
	rm -f "$AGHOME"/source/$f
	if test -f "$f"; then
		echo "Required file $f exists: size=`wc -c $f | awk '{print $1;}'` md5sum=`md5sum $f | awk '{print $1;}'`"
		cp $f "$AGHOME"/source/$f
	else
		echo "Required file $f not found."
	fi
done

cd "$AGHOME"/source

echo ""

if [ $TESTING ]
then
	if [ -f "$AGHOME"/submission_metadata.json ]
	then
		NAME=`jq .users\[0\].name "$AGHOME"/submission_metadata.json`
		EMAIL=`jq .users\[0\].email "$AGHOME"/submission_metadata.json`
		ASSIGNMENT=`jq -c .assignment.title "$AGHOME"/submission_metadata.json`
		echo Welcome "$NAME" to autograder for "$ASSIGNMENT"
		if [ "$EMAIL" != '"mbs@ee.ucla.edu"' ]
		then
			echo "Autograder is running in testing mode, and so exiting."
			cat results_default.json > "$AGHOME"/results/results.json
			exit 0
		else
			echo "Autograder is running in testing mode, but still proceeding because of special user."
		fi
	else
		echo "Autograder is running in testing mode, but still proceeding because of local execution."
	fi
else
	echo "Autograder is running in deployment mode!"
fi

echo "Autograder is in deployment mode"

echo wget -q -O final_part1_tb.circ https://www.dropbox.com/s/05oas17dsp61mbw/final_part1_tb.circ?raw=1
wget -q -O final_part1_tb.circ https://www.dropbox.com/s/05oas17dsp61mbw/final_part1_tb.circ?raw=1

echo wget -q -O final_part2_tb.circ https://www.dropbox.com/s/ukf0pabdfmparsd/final_part2_tb.circ?raw=1
wget -q -O final_part2_tb.circ https://www.dropbox.com/s/ukf0pabdfmparsd/final_part2_tb.circ?raw=1

echo wget -q -O M16\ Components.circ https://www.dropbox.com/s/9y78z196a0rbttd/M16%20Components.circ?raw=1
wget -q -O M16\ Components.circ https://www.dropbox.com/s/9y78z196a0rbttd/M16%20Components.circ?raw=1


LOGISIM=logisim-evolution-2.14.8.4-cornell.jar
FILES="final_part1_tb.circ final_part2_tb.circ"

for f in $FILES
do
	echo ""
#	java -jar logisim-evolution-2.14.8.4-cornell.jar $f -tty table 2>/dev/null | grep -v '1$' | cut -f 1-5 > da1_2_tb.out
	if test -f "$f"; then
		rm -f ${f%.*}.out
		echo "Running logisim on $f..."
		java -jar "$LOGISIM" "$f" -tty table 2>/dev/null 1> ${f%.*}.out
		#cat ${f%.*}.out
	else
		echo "File $f not available."
	fi
done

echo ""
echo "Downloading Python module for Logisim[logisim.py]."
rm -f logisim.py
wget -q -O logisim.py https://www.dropbox.com/s/imavgh8qmxkfmbv/logisim.py?raw=1

if [ ! -f logisim.py ]; then
    echo "Download of logisim.py failed!"
    cat results_error.json > "$AGHOME"/results/results.json
	exit 0
fi

echo "Downloading grading program [gen_results.py]."
rm -f gen_results.py
wget -q -O gen_results.py https://www.dropbox.com/s/welfuoihhlcara4/gen_results.py?raw=1

#echo "Bye"
#cat results_default.json > "$AGHOME"/results/results.json
#exit 0

grep EEM16 gen_results.py > /dev/null

if [ $? -ne 0 ]
then 
	echo "Error: problem in downloading gen_results.py."
	cat results_error.json > "$AGHOME"/results/results.json
else 
	echo "Running grading program [gen_results.py]."
	AGHOME="$AGHOME" python3 gen_results.py
fi